name: python-api-devops

on:
    push: 
      branches:
        - main
jobs: 
    test: 
      name: Run flake8 Linter
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v3
          
        - name: set up python
          uses: actions/setup-python@v4
          with:
             python-version: 3.10.0
           
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            
        -name: Run flake8
         run: flake8 main.py
         
   delivery:
     name: Build and push Docker image
     runs-on: ubuntu-latest
     needs: test
     steps:
       - name: checkout code
         uses: actions/checkout@v3
         
       - name: log in to Docker hub
         run echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
         
       - name: Build Docker image
         run: docker build -t ${{secrets.DOCKER_USERNAME}}/fastapi-app:latest .
         
       - name: Push Docker image 
         run: docker push ${{secrets.DOCKER_USERNAME}}/fastapi-app:latest